Solvro/web-planer

package-lock.json, package.json, src/components/ClassBlock.tsx, src/components/ClassSchedule.tsx, src/lib/types.ts, src/pages/index.tsx, src/pages/schedule.tsx, tailwind.config.ts
Szkielet planu, zamockowane jakieś kursy, będzie trzeba go trochę upiększyć, ale na razie imo wystarczy. Wrzuciłem tez tailwind-scrollbara.
=> feat: class schedule with mocked data

src/components/ClassBlock.tsx, src/components/ClassSchedule.tsx, src/components/Hour.tsx, src/lib/types.ts, src/pages/schedule.tsx, tailwind.config.ts
Plan działa tak jak rozmawialismy, czyli każda kolumna to 5 min 😎👍. Dodałem też siatkę godzin, plan wygląda teraz tak jak ze screena na dc. Nie bede zgrywał bohatera, Hour component i style do niego podjebałem z twojego repa. Imo wygląda to bardzo sexy w takim wydaniu w jakim jest teraz
=> Class schedule

src/components/ClassSchedule.tsx
* fix:styling
* -a
* fix:responsiveness
* fix:styling
=> fix:styling (#13)

src/pages/index.tsx
najwazniejsza zmiana w dziejach projektu
=> fix: added z-index to main index button

src/pages/index.tsx
Obecnie wyświetlała się informacja przejdź do planowania, co było mylące. Projekt startuje 10 września, więc została zamieszczona taka informacja
=> feat: inform about project deploy

frontend/src/components/Plan.tsx
=> fix: link fix

frontend/src/app/plans/create/[id]/_components/CreateNewPlanPage.tsx
fixnalem padding na podstronie kreatora
=> fix: padding

frontend/src/app/layout.tsx
This pull request includes changes to the `frontend/src/app/layout.tsx` file, focusing on replacing the `Head` component with the `Script` component and restructuring the layout to ensure proper script loading and component hierarchy.
Changes in layout and script loading:
* Replaced the `Head` component with the `Script` component to load external scripts (`frontend/src/app/layout.tsx`).
* Moved the script loading for analytics inside the `ClientProviders` component and adjusted the structure to ensure scripts are loaded correctly with the new `Script` component (`frontend/src/app/layout.tsx`).
=> fix: fix to umami fix

backend/app/controllers/auth_controller.ts, backend/app/controllers/schedules_controller.ts, backend/app/models/schedule.ts, backend/app/validators/schedule.ts, backend/database/migrations/1733392358905_create_schedule_courses_table.ts, backend/database/migrations/1733392588469_create_schedule_registrations_table.ts
This pull request introduces significant changes to the `SchedulesController` and related models, enhancing the handling of schedules, courses, and registrations. The most important changes include the addition of new relationships in the `Schedule` model, updates to the `SchedulesController` to handle these relationships, and the creation of new database tables to support these changes.
Enhancements to `SchedulesController`:
* [`backend/app/controllers/schedules_controller.ts`](diffhunk://#diff-ae488a05ca0be6532467a3a0b2eb4ce34b6bf029a9141ef8116ba93dc4da85b4L51-R94): Updated the `SchedulesController` to preload `registrations` and `courses`, transform the schedule data structure, and synchronize `registrations` and `courses` when updating a schedule. …
=> feat: add relations to courses and registrations

backend/app/controllers/schedules_controller.ts
This pull request includes significant changes to the `SchedulesController` in `backend/app/controllers/schedules_controller.ts`. The updates improve the handling of schedules by adding preloading of related data and better error handling for schedule deletion.
Improvements to schedule handling:
* Added preloading of `registrations` and `courses` for each schedule, and transformed the schedules to include related course groups. This ensures that all necessary related data is loaded and structured correctly.
Enhanced error handling:
* Wrapped the schedule deletion logic in a `try-catch` block to handle cases where the schedule might not be found, returning a more informative message on success or failure.
=> feat: add more data in all schedules get

frontend/src/app/api/callback/route.ts, frontend/src/app/plans/preview/[id]/page.client.tsx, frontend/src/app/plans/preview/[id]/page.tsx, frontend/src/components/class-block.tsx, frontend/src/components/plan-item.tsx, frontend/src/components/registration-combobox.tsx, frontend/src/components/ui/status-icon.tsx, frontend/src/lib/utils/generate-ics-file.ts
fixy z dc plus od siebie dolozylem fixa na pokazywanie planow od razu po zalogowaniu
i ogolnie dawido chcial zeby w itemach kursow bylo mniej tekstu i ikonki, wiec na dostepne miejsca dalem ikonke ludzikow a na ocene zamiast tekstu zdjalem z gory gwiaxkdi i dalem jako ikonke, ale zmienilem ze jesli ocena to 0 to chociaz jedna sie pokazuje zeby cos bylo, a tak bedzie tyle gwiazdek jaka ocena
=> fix: minor fixes and changes

backend/app/scrap-lecturers/scrap_lecturers.ts, backend/commands/lecturers.ts
Add polwro scraper and insert results to database
=> Add polwro scraper

frontend/src/app/plans/edit/[id]/page.client.tsx, frontend/src/components/class-block-stars.tsx, frontend/src/components/class-block.tsx, frontend/src/components/groups-accordion.tsx, frontend/src/lib/types.ts, frontend/src/lib/utils/update-local-plan.ts, frontend/src/types/index.ts
redesign gwiazdek, itemu grup i dodalem ilosc opinii, oraz jesli jest za maly to nie ma wizualizacji gwiazdek
=> feat: little redesign

frontend/package-lock.json, frontend/package.json
=> chore: nextjs version bump

frontend/src/app/plans/account/layout.tsx
=> fix: another fix to footer

frontend/package-lock.json, frontend/package.json, frontend/src/app/plans/preview/[id]/page.client.tsx
libka: [https://www.npmjs.com/package/html-to-image](url)
=> feat: export to jpg

backend/config/cors.ts
This pull request includes changes to the `backend/config/cors.ts` file to enhance the configuration of the CORS policy by incorporating environment variables.
Changes to CORS configuration:
* [`backend/config/cors.ts`](diffhunk://#diff-fa00dc7bed30ada8a6fde3b30bd14a04557550df47ac179663c72b1ca24bc273R3-R4): Imported `env` from `#start/env` to use environment variables in the CORS configuration.
* [`backend/config/cors.ts`](diffhunk://#diff-fa00dc7bed30ada8a6fde3b30bd14a04557550df47ac179663c72b1ca24bc273L11-R13): Modified the `origin` property to use the `CORS_ORIGIN` environment variable, defaulting to "planer.solvro.pl", and split it into an array.
=> feat: add cors

frontend/src/app/(homepage)/_components/github-repo.tsx, frontend/src/app/(homepage)/page.tsx, frontend/src/app/plans/edit/[id]/page.client.tsx, frontend/src/components/magicui/animated-text.tsx, frontend/src/components/solvro-logo.tsx
This pull request includes several changes to improve the homepage and its components. The most important changes include adding external links, removing unnecessary code, and updating component types.
Improvements to the homepage:
* [`frontend/src/app/(homepage)/_components/github-repo.tsx`](diffhunk://#diff-644b352407a162cf84feef5d86dca0c2c5cab4d56faf276129644252823bb5c8R1-R2): Added `Link` component to wrap the GitHub button, allowing users to open the GitHub repository in a new tab. [[1]](diffhunk://#diff-644b352407a162cf84feef5d86dca0c2c5cab4d56faf276129644252823bb5c8R1-R2) [[2]](diffhunk://#diff-644b352407a162cf84feef5d86dca0c2c5cab4d56faf276129644252823bb5c8R94-R101)
* [`frontend/src/app/(homepage)/page.tsx`](diffhunk://#diff-bca11ce019c3f76137ffe96d403b56a5d5535b9d41ebcf8264130361c …
=> feat: new topwr section and link fix

frontend/src/app/plans/edit/[id]/_components/hide-days-settings.tsx, frontend/src/app/plans/edit/[id]/page.client.tsx
This pull request includes several changes to the `frontend/src/app/plans/edit/[id]` directory, focusing on improving the handling of the `hideDays` setting and modifying the initial state of checkboxes. The most important changes include adding a `useRef` and `useEffect` to manage the `hideDays` state, removing redundant code, setting checkboxes to be checked by default, and adjusting the display logic for class schedules based on the `hideDays` setting.
Improvements to `hideDays` state management:
* `frontend/src/app/plans/edit/[id]/_components/hide-days-settings.tsx`: Added `useRef` and `useEffect` to initialize `hideDays` from localStorage only once when the component is first rendered. ([frontend/src/app/plans/edit/[id]/_components/hide-days-settings.tsxL2-R2](diffhunk://#diff-1d7a392 …
=> feat: check all courses by default

frontend/package-lock.json, frontend/package.json, frontend/src/app/globals.css, frontend/src/app/plans/_components/plans-topbar.tsx, frontend/src/app/plans/edit/[id]/_components/app-sidebar.tsx, frontend/src/app/plans/edit/[id]/page.client.tsx, frontend/src/app/plans/layout.tsx, frontend/src/components/class-schedule.tsx, frontend/src/components/icons.tsx, frontend/src/components/ui/sheet.tsx, frontend/src/components/ui/sidebar.tsx, frontend/src/hooks/use-mobile.tsx, frontend/src/lib/use-plan.ts, frontend/tailwind.config.ts
This pull request includes various updates and improvements to the `frontend` package, primarily focusing on updating dependencies and enhancing the user interface. The most important changes include updating the `@radix-ui/react-dialog` package and its dependencies, adding new CSS variables for the sidebar, and modifying the `PlansTopbar` component to include a sidebar trigger and improve styling.
User Interface Enhancements:
* Added new CSS variables for the sidebar in `frontend/src/app/globals.css` to improve customization and theming. [[1]](diffhunk://#diff-87958537a79d51d35702beb783d9e8a8aea8d2b455ce6f65fb5e3cce3061318fR28-R36) [[2]](diffhunk://#diff-87958537a79d51d35702beb783d9e8a8aea8d2b455ce6f65fb5e3cce3061318fR59-R67)
* Modified the `PlansTopbar` component to include a …
=> feat: collapsible sidebar at plan edit view & ui fixes

docker-compose.build.yml, docker-compose.yml
this may require manual intervention for anyone running these: you will need to create a backup, delete old database files and load from backups again
=> feat: upgrade postgres in composefiles to 17

frontend/src/app/plans/page.client.tsx, frontend/src/components/plan-item.tsx
=> feat: registrations count in plan item
